### ISSUE TITLE
Do we actually need an explicit  bounding box input type?

### ISSUE THREAD

**Issue by pvretano** [opengeospatial/wps-rest-binding#15]
Since we can have complex data input, do we actually need a bounding box input type?  Couldn't bounding box input simply be another type of complex data input?

**Comment by spacebel** [comment]
As there are no particular handling by the server of such input, it has always been my feeling. And the bounding box format can be provided by indicatinig the right mimeType (addtional mimeType ma be defined if needed).

**Comment by alpha-beta-soup** [comment]
The typical use-case for a bounding box input would be as some kind of selection, i.e. "only process within this bounding box". This begs the question of why such an operation should be limited to rectangular shapes rather than a more generic intersection selection, i.e. "only process within this shape" or "only process along this line". So I think that there's no real justification for a special bounding box input type, when it could be handled by a "complex" input of an arbitrary geometry, which could include a bounding box geometry.

**Comment by bpross-52n** [comment]
This is part of a cross-SWG coordination effort: https://github.com/opengeospatial/oapi_common/issues/43
