### ISSUE TITLE
Add exception to status response

### ISSUE THREAD

**Issue by m-mohr** [opengeospatial/wps-rest-binding#32]
There's an endpoint `GET /processes/{id}/jobs/{jobID}/exception` that returns the exception details in case a job failed. 

I think it would be easier to add the exception information to the status information at `GET /processes/{id}/jobs/{jobID}` and remove the `GET /processes/{id}/jobs/{jobID}/exception` endpoint.

Example: 
```json
{
  "status": "failed",
  "message": "string",
  "progress": 75,
  "exception": {
    "code": "123",
    "description": "A very informative error message..."
  },
  "links": []
}
```

This would avoid an additional request to `GET /processes/{id}/jobs/{jobID}/exception` in case of errors and nicely couples status information at one place.

**Comment by m-mohr** [comment]
In addition, the exception should be in the response of the result request or the synchronous post request to the job if the job failed.

Of course, errors should be transmitted with a 400/500 error code and not with code 200 as in https://github.com/opengeospatial/wps-rest-binding/blob/master/openapi.yaml#L290

**Comment by francbartoli** [comment]
I'm much more convinced we should need to give always `201` with `POST /processes/{id}/jobs` and then in case of errors/exceptions to have:

```
{
    "message": "Process finished",
    "links": [
        {
            "href": "http://localhost/api/v1/wps/processes/buffer/jobs/15124658-d48b-4333-acc7-8d2332f7d2fd",
            "rel": "self",
            "type": "application/json",
            "hreflang": "en-US",
            "title": "This document"
        },
        {
            "href": "http://localhost/api/v1/wps/processes/buffer/jobs/15124658-d48b-4333-acc7-8d2332f7d2fd/results/exception",
            "rel": "exception",
            "type": "application/json",
            "hreflang": "en-US",
            "title": "Process exception"
        }
    ],
    "status": "failed",
    "progress": 100
}
```

Please note the plural forms as suggested by #21. To give more value to this choice I would consider this complex use case:

- in this case, the client has a state of the execution and in a workflow/process chaining scenario it might decide to execute again the job that failed and then continue with the next process in the pipeline
- on the other hand, the HTTP status might be considered wrong but at the end of the day the resource which is your `jobID` has been created and you have a `Location` when you can find result/exception

**Comment by bpross-52n** [comment]
:+1 for plural form `results`

**Comment by m-mohr** [comment]
+1 on results in plural form, but I don't agree with sending out errors as success error code. So you'd need to parse the response to figure out whether it's an error or not. That could lead to a client that needs to parse large results just to find out it's not an error.

**Comment by alpha-beta-soup** [comment]
I'm not sure I'm convinved that it's appropriate that the `GET /processes/{id}/jobs/{id}/results` "shall have a HTTP error code that corresponds to the reason of the failure". For instance, to return a 400 error code for the `/results` endpoint when it correctly/successfully returns a job failure result feels a bit odd. I do see the logic of it, but at the same time I intuituively expect a 200 status for that case, since *that particular request* (for the result) was successful, even if the job itself was not. The spec seems to suggest that a 200 status is correct when returning the ["result of a job"](https://github.com/opengeospatial/wps-rest-binding/blob/master/openapi.yaml#L247), and a failure is still some kind of result. That said, I'm also not convinced by returning a 200 status in this case... it's quite a conundrum.

**Comment by alpha-beta-soup** [comment]
I'm not sure I'm convinved that it's appropriate that the `GET /processes/{id}/jobs/{id}/results` "shall have a HTTP error code that corresponds to the reason of the failure". For instance, to return a 400 error code for the `/results` endpoint when it *correctly/successfully* returns *a job failure result* feels a bit odd. I do see the logic of it, but at the same time I intuituively expect a 200 status for that case, since *that particular request* (for the result) was successful, even if the job itself was not. The spec seems to suggest that a 200 status is correct when returning the ["result of a job"](https://github.com/opengeospatial/wps-rest-binding/blob/master/openapi.yaml#L247), and a failure is still some kind of result. That said, I'm also not convinced by returning a 200 status in this case... it's quite a conundrum.

Does any have a particulalry prescient insight to share on this?

---

I also favour `result` over `results`, since the output is of a singular job, but I don't think that's particularly troubling either way.

**Comment by bpross-52n** [comment]
I need to think about this a bit more. At least it should be made absolutely clear what HTTP response code to expect when. 
The change to results was made to be consistent with the other path elements (processes/{id}/jobs/{id}/results, all plural)

**Comment by bpross-52n** [comment]
Discussed in telecon on Aug 17. Adressed in current draft.4
